#!/usr/bin/env python3

import openai,os,sys

while True:
	query=input("query: ")
	if query=="exit":
		break
	if query=="clear":
		os.system("clear")
		continue
	openai.api_key = os.environ['api_key']
	completions = openai.Completion.create(
		engine="text-davinci-003",
		prompt=query,
		max_tokens=1024,
		n=1,
		stop=None,
		temperature=0.5,
	)

	message = completions.choices[0].text
	print("response: %s\n" % message)

